dist: xenial
language: php
env:
  global:
    - SETUP=stable
    - secure: UNVf5tUIfg4Fs5o07dir/2iQK+KYXx23pYr8+Eova9wF0qxM2hGq+Ruxd8PmbbeUpSA+GOUYFKeZ0K5vETD+63Q8dmlT4phObFwvf3tT9a6N0KeN3BUiOop2p8v20jXdj+MpqaeW//f1efSwqKhKAfFRlxqqMMwGqUNUpGeMoq9wva7jcRMn/SWvm3epOvqbCjCOrEi3RXAagnMlb5+Q/JqXlaL8jIY8pmidkO0/srj5JEkIF5V5cB5DLITeYUI5tm2gVbv2KI1N1LtYLjtPFfsGz4g0S2znFkOqAjeKtAQ82GS8E61YGxm3IFwbBZDwMUb0k3qnV0tbsyi+fEckFs3UFRmu8tUsh78H0u+0246GlewSLVwQGZ9K2tnSTm2sYFI5dwM4S8GKm1H9+Kr9IIATvJpi8rEIoaHWUFCz/6/1jeTd0MR2T6l/NRRXKHq0BftCcU6z4B0VKd4CS9DBEBebKVTPVkRlZT2iKRMLgL8Lut0abU+fkbzy2XU/sc5uVe73NbMoQ1+zXKmd565PmDGbYUeJKbf2+XZEEGY1P2tNoVUT7E8K7qtcGiuG+WGRNh01l7JuD8hgo7wG0aPfFbG/Kb73dylKXv3zj97LktLlOREI2oD1jmd7sUGy/ez2+L/aP6WAPvVbxoMoT/Psv1d8v8x0U0bDvDhFRIGEAjQ=
    - secure: pw7SuYWTJE5LP+J6+IJDlHOLNL94ioKpqkot/s7c9YJjU7h/mMxRH0zGFjBUsM4uWHY1zaIJ4cuVtrUH5RWfL8AwCAp2clKS2GByLp3u4sDdjCn4KN8fUd52K6OpPrxcDThjoQh/0nRJb0369YFffcqTKQeE3r7MTnxFaNWQi+azMphZajLDMSezZ/EJCBnizAFlTGaEiZuXUDUDCb1p6o0vHnDrCQd8j4ZnRqVMDgvOdRxqZelXkrriPVDR1zQDNoCiCro3IyOR1JxMihH5unbNuMkgVpn0yLpRtSQOmH6c1lCvXTMQl0D7dP400LqbbvamX+IHmUKutR0XxgIbRpO/rPKVvItNlLyxPUbJK5bTubdMEWAQh+FUeVKdHe2BRorM46n8obgOmVRk6Xr79botQ18domrX/fz2kkpw9ocuO4ZFjYDhFael+sl81k3Ak8xzGp/4qdQbfYq/z4g8+hBzm69mGTZHdbotc8lf2dGVs53P+oQwFumZO6sXQL+rjs5Dp9HIQMSNaULFOH74dJQ6dfAvKI1583OPIYbvSFiFCxzEskOOZ3Bwvi1e/5vUJkOa57fdKTgDwYwbHibzVE5Mxg563SLnTMcFGCOm9N5sx2v65uK53ra4P4HVsUxFeAPGlMt9tc3BRfLYZtSbyaHaDeTR9o3CuJ4uKgl/AoI=

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: SETUP=lowest
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest
    - php: 7.4snapshot
    - php: 7.4snapshot
      env: SETUP=lowest

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit
