dist: xenial
language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: ./vendor/bin/phpunit tests
