dist: xenial
language: php
env:
  global:
    - SETUP=stable
    - secure: UNVf5tUIfg4Fs5o07dir/2iQK+KYXx23pYr8+Eova9wF0qxM2hGq+Ruxd8PmbbeUpSA+GOUYFKeZ0K5vETD+63Q8dmlT4phObFwvf3tT9a6N0KeN3BUiOop2p8v20jXdj+MpqaeW//f1efSwqKhKAfFRlxqqMMwGqUNUpGeMoq9wva7jcRMn/SWvm3epOvqbCjCOrEi3RXAagnMlb5+Q/JqXlaL8jIY8pmidkO0/srj5JEkIF5V5cB5DLITeYUI5tm2gVbv2KI1N1LtYLjtPFfsGz4g0S2znFkOqAjeKtAQ82GS8E61YGxm3IFwbBZDwMUb0k3qnV0tbsyi+fEckFs3UFRmu8tUsh78H0u+0246GlewSLVwQGZ9K2tnSTm2sYFI5dwM4S8GKm1H9+Kr9IIATvJpi8rEIoaHWUFCz/6/1jeTd0MR2T6l/NRRXKHq0BftCcU6z4B0VKd4CS9DBEBebKVTPVkRlZT2iKRMLgL8Lut0abU+fkbzy2XU/sc5uVe73NbMoQ1+zXKmd565PmDGbYUeJKbf2+XZEEGY1P2tNoVUT7E8K7qtcGiuG+WGRNh01l7JuD8hgo7wG0aPfFbG/Kb73dylKXv3zj97LktLlOREI2oD1jmd7sUGy/ez2+L/aP6WAPvVbxoMoT/Psv1d8v8x0U0bDvDhFRIGEAjQ=
    - secure: l6q9E0JpapzNsIaGI20/EqewS/NsAD09yO6StZZxkfjMw7mWOdo6CstZqSKNtIGGD8ygl2L7MWuy4aBSSxz4zrSqFwFaSzSzQ2BE9BJMXNtdSKPv1Zpd9E4FakiiY3Dbu6+6HZ3AOAs4G/VlHqb3AA5tkn1GJGHNSEYzg/CzG8A0VDr/Whn/a0ABUNNa+YCFpr2sWWBgmVx0umsEl8+OE7uC14prv1G2ageo9xq5in4lRbhppAg793DVRsxrj63qz6tYTQywDqCmvi/LZw39iJdQ8//YMsbcWGA0Hww88+5ZobhrP32UJ6+iWVyf98fK8JXpMEVmu++02gFbrTFosondPS6ChbowVyYRX3XtgD8F+dJMpTcVgYTBJ7t9vP4w/wyJvrhsgyQ+UP+XkEm3aJVlU5UnnNj8oSO0PNCN7552CW1+1pNxz7OMNcNDdjsCCYVOS42TenlKJosoDFC/cD8+C8Ji8/Oj2I+fZ8JLMzu7X2VE0qimDlaUKyGibCPmKePphXZqaYXn+tr2K2zmHk0lW5bQrMhT9AmGIwIYrI/uwNNI0oL1CysoLb+kaucREKwDrdV0UlxWJnsTFoGPRyLrQJ5H5x27bcM58W6RS7MfvgCdDvlFA/RbjCKqXtilsB+EcxDixgy8FAO3ydC3GWhunf9GWA1uIHgAg9Gnark=

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: SETUP=lowest
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest
    - php: 7.4snapshot
    - php: 7.4snapshot
      env: SETUP=lowest

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit
